# Generated by Django 6.1.1 on 2026-09-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField()),
                ('environment_type', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('STAGING', 'Staging'), ('PRODUCTION', 'Production')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'key'), name='unique_environment_key_per_project')],
            },
        ),
    ]
